### ISSUE TITLE
Howto resolve 'The given key (NServiceBus.LocalAddress) was not present in the dictionary.'

### ISSUE THREAD

**Issue by ramonsmits** [Particular/docs.particular.net#1183]
When using V5 and the NServiceBus.Host and you get this exception the fix for it is to run `Add-BindingRedirect` in the package manager console, then create an `NServiceBus.Host.exe.config` file and copy the `configuration/runtime` section into it.

We have to put this somewhere. Probably in http://docs.particular.net/nservicebus/hosting/nservicebus-host/#application-domains as one of known issues.

**Comment by SimonCropp** [comment]
@ramonsmits couldnt the same happen when not using the NSB host?

**Comment by SimonCropp** [comment]
@ramonsmits is this still a problem in v6?

**Comment by SimonCropp** [comment]
Assuming no response means it is not an issue in v6

**Comment by ramonsmits** [comment]
@SimonCropp I don't know if this is still an issue in V6. The host is still using the same concepts to you still need to 'clone' the generated assembly redirects to the `NServiceBus.Host.exe.config` and that guidance is mentioned in the linked section.

**Comment by SimonCropp** [comment]
@ramonsmits can u please verify?

**Comment by stokedout** [comment]
Old question now but this caught me out. I found it was when we configured NServiceBus to use Profiles but we didn't pass the profile name as an argument.

**Comment by SzymonPobiega** [comment]
@stokedout which versions of NServiceBus / Host do you use?

**Comment by stokedout** [comment]
@SzymonPobiega we are using NServiceBus 5.2.25. It's not an issue as such but it would be useful if you could tell us how to display a more meaningful error message when the profile name is missing. 

```
System.Collections.Generic.KeyNotFoundException: The given key (NServiceBus.LocalAddress) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 91
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 23
   at NServiceBus.SettingsExtentions.LocalAddress(ReadOnlySettings settings) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\SettingsExtentions.cs:line 66
   at NServiceBus.Features.TimeoutManager.Setup(FeatureConfigurationContext context) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Timeout\TimeoutManager.cs:line 40
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Features\FeatureActivator.cs:line 240
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Features\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.Create(BusConfiguration configuration) in C:\BuildAgent\work\a93f853f0c1b9532\src\NServiceBus.Core\Bus.cs:line 17
   at NServiceBus.GenericHost.PerformConfiguration(Action`1 moreConfiguration) in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 119
   at NServiceBus.GenericHost.Start() in c:\BuildAgent\work\a3de8759ee491634\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 58
```

**Comment by SzymonPobiega** [comment]
@stokedout Unfortunately V5 is on extended support which means we are only going to fix critical bugs in it so we are probably not going to fix this issue.
