### ISSUE TITLE
Feedback: 'NServiceBus Mailer'

### ISSUE THREAD

**Issue by SimonCropp** [Particular/docs.particular.net#3067]
Feedback for 'NServiceBus Mailer' https://docs.particular.net/samples/mailer/

Location in GitHub: https://github.com/Particular/docs.particular.net/blob/master/samples/mailer/sample.md

ping @HEskandari
```
System.Collections.Generic.KeyNotFoundException occurred
  HResult=0x80131577
  Message=The given key (MainSerializer) was not present in the dictionary.
  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 94
   at NServiceBus.Settings.SettingsHolder.Get[T](String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 20
   at NServiceBus.Mailer.MailerFeature.GetDefaultSerializer(ReadOnlySettings settings) in C:\projects\nservicebus-mailer\NServiceBus.Mailer\MailerFeature.cs:line 61
   at NServiceBus.Mailer.MailerFeature.Setup(FeatureConfigurationContext context) in C:\projects\nservicebus-mailer\NServiceBus.Mailer\MailerFeature.cs:line 37
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, IConfigureComponents container, PipelineSettings pipelineSettings, RoutingComponent routing) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 194
   at NServiceBus.Features.FeatureActivator.SetupFeatures(IConfigureComponents container, PipelineSettings pipelineSettings, RoutingComponent routing) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 57
   at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\InitializableEndpoint.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 27
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<AsyncMain>d__2.MoveNext() in C:\Downloads\mailer_mailer_3\Endpoint\Program.cs:line 70
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.Main() in C:\Downloads\mailer_mailer_3\Endpoint\Program.cs:line 16

```

**Comment by HEskandari** [comment]
Thanks for reporting it. I'll have a look at it hopefully this Wednesday.

**Comment by SimonCropp** [comment]
ping @HEskandari
