### ISSUE TITLE
Cannot run Azure Self Hosting sample?

### ISSUE THREAD

**Issue by paulsaxton** [Particular/docs.particular.net#3327]
Hello

I get the error below when running the Azure Self Hosting sample

System.Exception occurred
  HResult=0x80131500
  Message=Could not enumerate all types for 'NServiceBus.Azure.Transports.WindowsAzureStorageQueues, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
It looks like you may be missing binding redirects in the config file for the following assemblies:
Microsoft.WindowsAzure.Storage, Version=8.4.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
For more information see http://msdn.microsoft.com/en-us/library/7wd6ex19(v=vs.100).aspx

  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.Hosting.Helpers.AssemblyScanner.ScanAssembly(Assembly assembly, AssemblyScannerResults results)
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies()
   at NServiceBus.EndpointConfiguration.GetAllowedTypes(String path)
   at NServiceBus.EndpointConfiguration.Build()
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WorkerRole.<StartEndpoint>d__1.MoveNext() in C:\Source\GitHub\docs.particular.net\samples\azure\self-host\Core_6\HostWorker\WorkerRole.cs:line 75
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WorkerRole.OnStart() in C:\Source\GitHub\docs.particular.net\samples\azure\self-host\Core_6\HostWorker\WorkerRole.cs:line 16
   at Microsoft.WindowsAzure.ServiceRuntime.RoleEnvironment.InitializeRoleInternal(RoleType roleTypeEnum)
   at Microsoft.WindowsAzure.ServiceRuntime.Implementation.Loader.RoleRuntimeBridge.<InitializeRole>b__0()

Whats the cause of this?

Paul

**Comment by SimonCropp** [comment]
ping @Particular/azure-maintainers

**Comment by SeanFeldman** [comment]
sample: https://docs.particular.net/samples/azure/self-host/

**Comment by danielmarbach** [comment]
@paulsaxton 

Interesting. Could you give us a bit more information about the environment you are running the sample? I've tested the sample with

VS2017 15.3.3 and higher
Azure SDK 2.9 and higher
Azure Storage Emulator 5.2 and higher

Cloud Services don't generate the necessary redirects automatically. We had to put them into the provided app.config. Can you check whether the storage SDK that is referenced in the output folder is latest 8.4?

**Comment by paulsaxton** [comment]
I think its 8.5 now 

I got it compiling and running adding this to the config

<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
        <dependentAssembly>
          <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" />
          <bindingRedirect oldVersion="0.0.0.0-8.4.0.0" newVersion="8.5.0.0" />
        </dependentAssembly>
      </assemblyBinding>            

Its now deploying to the Azure :)

Although I am not sure what to do to see it working!

**Comment by danielmarbach** [comment]
Ok I will update the sample, thanks for reporting

**Comment by danielmarbach** [comment]
@Particular/docs-maintainers @Particular/azure-maintainers should we lock the sample to specific versions of the referenced nuget packages since auto-generated assembly redirects are not working with Cloud Services? // cc @SimonCropp

**Comment by danielmarbach** [comment]
Sent in https://github.com/Particular/docs.particular.net/pull/3332. Currently only locking down Azure Storage. Thoughts?

**Comment by weralabaj** [comment]
I don't see a downside, IMO most important thing is that the user doesn't have to struggle with running the sample. If you think it's necessary, we may add a note in the sample description saying we did this and why.

**Comment by SimonCropp** [comment]
@paulsaxton that sample has had some fixes applied to the package references and should now work for you. please let u know id u have any more trouble.
