### ISSUE TITLE
Startup diagnostics error level

### ISSUE THREAD

**Issue by neumn** [Particular/docs.particular.net#4766]
Feedback for 'Startup diagnostics' https://docs.particular.net/nservicebus/hosting/startup-diagnostics

If setting up the diagnostics part is not blocking, i would put the level of the error on Warn.

See following error. (Since we did the upgrade to nsb v7)

```
2020-04-03 10:07:25,975 [5] ERROR NServiceBus.HostStartupDiagnostics - Unable to create the diagnostics output directory. Check the attached exception for further information, or change the diagnostics directory using 'EndpointConfiguration.SetDiagnosticsPath()'.
System.UnauthorizedAccessException: Access to the path 'd:\Services\xyz\.diagnostics' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at NServiceBus.HostStartupDiagnostics.BuildDefaultDiagnosticsWriter(ReadOnlySettings settings)
```

**Comment by ramonsmits** [comment]
@neumn To not have it generate a error log entry you can implement a custom diagnostics writer and do nothing as shown here: https://docs.particular.net/nservicebus/hosting/startup-diagnostics#writing-to-other-targets

Does that help for now?

I've also created a PR https://github.com/Particular/NServiceBus/pull/5615 as I think this should be a WARNING.

**Comment by neumn** [comment]
It's ok, Thanks.
